[WAGON-638] Drop deprecated providers
apache/maven-wagon pull request #133
Opened 2024-12-26 17:12 UTC by slachiewicz

2024-12-27 10:12 UTC, michael-o commented
The WebDAV provider can only be dropped when its functionality has been folded into the HTTP one, unless we say we drop WebDAV altogether...

2024-12-27 11:31 UTC, slachiewicz commented
good point Michael. This removal will also affect plugin https://github.com/mojohaus/wagon-maven-plugin

2024-12-28 12:37 UTC, michael-o requested changes
The WebDAV provider needs to be retained until it is foled.

2024-12-31 10:45 UTC, closed without merging

2025-07-03 06:55 UTC, jira-importer commented
Resolve #761