[MNG-6829] Replace any StringUtils#isEmpty(String) and #isNotEmpty(String)
apache/maven-wagon pull request #90
Opened 2023-05-10 11:29 UTC by timtebeek

Continuation of https://issues.apache.org/jira/browse/MNG-6829

Review requested of @elharo

Use this link to re-run the recipe: https://public.moderne.io/recipes/org.openrewrite.java.migrate.apache.commons.lang.IsNotEmptyToJdk?organizationId=QXBhY2hlIE1hdmVu

2023-05-10 12:32 UTC, elharo approved these changes

2023-05-10 12:32 UTC, elharo commented on wagon-provider-test/src/main/java/org/apache/maven/wagon/http/HttpWagonTestCase.java
> +                success &= expectedResponseCodes[i] == handlerRequestResponses.get( i ).responseCode;
This change isn't wrong, but doesn't seem related to isEmpty methods. What's happening?

2023-05-10 13:46 UTC, elharo requested changes
IT failure could be related:

Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check (checkstyle-check) on project wagon-provider-test: You have 12 Checkstyle violations. -> [H

2023-05-10 22:19 UTC, timtebeek commented
The checkstyle violations would need a manual fix; could pick this up again later.

2023-05-14 11:33 UTC, elharo approved these changes

2023-08-15 07:47 UTC, slachiewicz approved these changes

2023-08-15 07:47 UTC, merged